version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports: # appサービスからは直接ポートを公開しない (Nginxが8080を公開するため)
    #   - "8080:80"
    volumes:
      - .:/var/www/html:delegated
    environment:
        - FUEL_ENV=development 
        - FUEL_BASE_PATH=/var/www/html/fuel/
    depends_on:
      - db
      # Nginxサービスが追加されるので、Nginxもdepends_onに追加するべきだが、
      # Nginxがappに依存するので、循環依存を避けるためappからは削除
    dns:
      - 8.8.8.8
      - 1.1.1.1

  nginx: # <-- 新しく追加するNginxサービス
    image: nginx:stable-alpine # 軽量なNginxイメージ
    ports:
      - "8080:80" # ホストの8080ポートをNginxの80ポートにマッピング
    volumes:
      - .:/var/www/html:delegated # アプリケーションコードをマウント
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # Nginx設定ファイルをマウント
    depends_on:
      - app # Nginxはapp (php-fpm) に依存
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: monitor_system
      MYSQL_USER: fuelphp_user
      MYSQL_PASSWORD: fuelphp_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
        
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8081:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root_password
      depends_on:
        - db

volumes:
  db_data: